version: "3.9" 
services:
  synapse:
    image: lambdatest/synapse:latest
    stop_signal: SIGINT
    restart: always
    networks:
      - test-at-scale
    hostname: synapse
    container_name: synapse
    volumes:
      # synapse will needs socket access to create containers on host
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/synapse:/tmp/synapse"
      - ".synapse.json:/home/synapse/.synapse.json"
      - "/etc/machine-id:/etc/machine-id"

networks:
  test-at-scale:
    external: false
    name: test-at-scale
